name: drop_shadow
description: A new Flutter package for creating drop shadow of any widget with a lot of properties to make it look much good.
repository: https://github.com/iisprey/drop_shadow
issue_tracker: https://github.com/rei-codes/drop_shadow/issues
version: 0.1.0

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^4.0.0+1

screenshots:
  - description: 'Drop shadow example of the package'
    path: images/cover.webp
